# # Use lightweight Python base
# FROM python:3.10-slim

# # Set working directory
# WORKDIR /app

# # Install system dependencies for psycopg2
# RUN apt-get update && apt-get install -y \
#     build-essential \
#     libpq-dev \
#  && rm -rf /var/lib/apt/lists/*

# # Copy dependency list first (for layer caching)
# COPY requirements.txt .

# # Install dependencies
# RUN pip install --no-cache-dir -r requirements.txt

# # Copy application code
# COPY . .

# # Expose app port
# EXPOSE 8000

# # Start with Gunicorn in production
# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]


FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 8000
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
