apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: istio-cert-pool
spec:
  acme:
    email: nayanzagade71@gmail.com
    privateKeySecretRef:
      name: bookinfo-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: bookinfo-gateway
            namespace: default
---                
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookinfo-cert
  namespace: istio-system   
spec:
  secretName: bookinfo
  issuerRef:
    name: istio-cert-pool
    kind: ClusterIssuer
  dnsNames:
  - istio-test.nayanzagade.xyz 