apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: nayanzagade7/otel-db:latest # could be postgres/mysql or dummy
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: default
spec:
  selector:
    app: database
  ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
  type: ClusterIP
